feat: switch build to tsup, change default to esm, fix related issues
solidjs/solid-testing-library pull request #11
Opened 2022-07-17 10:27 UTC by benbender

This PR switches the build-tool to tsup and removes the custom build-setup. It switches the default-build to esm to align `solid-testing-library` with the rest of the ecosystem.

2022-07-19 04:02 UTC, modderme123 commented
Jest used to require CJS builds (because CJS can't import ESM). If you have time, it would be great to check that this still works with Jest.

2022-07-19 05:56 UTC, benbender commented
Sure thing! I grabbed https://github.com/yeunhakim93/solid-js-app (first result for `solid-testing-library` + `jest` withe green tests + jest), removed `solid-testing-library` from `node_modules` and linked my branch. Ran without problems.

I'm unsure if there is a way to automate this without pulling in massive extra infrastructre. If you have any idea on that, I would try to provide an automated test.

2022-07-19 06:40 UTC, modderme123 approved these changes

2022-11-05 21:04 UTC, atk requested changes

2022-11-05 21:04 UTC, atk commented on tsconfig.json
> +	"jsx": "preserve",
What's with the extra space?

2022-11-06 19:59 UTC, atk commented
I have based my last updates on your work and fixed a few minor errors. Thanks for your PR, it saved me a lot of time!

2022-11-06 19:59 UTC, closed without merging